//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reserva.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Armamento : Material
    {
        public int Id { get; set; }
        public string NSerie { get; set; }
        public string Modelo { get; set; }
        public int MunicaoId { get; set; }
    
        public virtual Municao Municao { get; set; }
    }
}
