//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reserva.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Material
    {
        [Key]
        public int Tombo { get; set; }
        public int AlmoxarifadoId { get; set; }
        public bool Disponivel { get; set; }
        public int FabricanteId { get; set; }
    
        public virtual Almoxarifado Almoxarifado { get; set; }
        public virtual Cautela Cautela { get; set; }
        public virtual Fabricante Fabricante { get; set; }
    }
}
