//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reserva.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Militar
    {
        public int Id { get; set; }
        public string Nome { get; set; }
        public string NomeGuerra { get; set; }
        public string Matricula { get; set; }
        public int PatenteId { get; set; }
    
        public virtual Patente Patente { get; set; }
    }
}
