//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reserva.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Operacao
    {
        public int Id { get; set; }
        public bool Cautelado { get; set; }
        public int CautelaId { get; set; }
        public int MaterialTombo { get; set; }    
        public virtual Cautela Cautela { get; set; }
        public virtual Material Material { get; set; }
        public string DescricaoMaterial { get; set; }
    }
}
