//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reserva.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ReservaBDEntities : DbContext
    {
        public ReservaBDEntities()
            : base("name=ReservaBDEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Almoxarifado> Almoxarifadoes { get; set; }
        public virtual DbSet<Militar> Militars { get; set; }
        public virtual DbSet<Patente> Patentes { get; set; }
        public virtual DbSet<Material> Materiais { get; set; }
        public virtual DbSet<Fabricante> Fabricantes { get; set; }
        public virtual DbSet<Calibre> Calibres { get; set; }
        public virtual DbSet<Cautela> Cautelas { get; set; }
        public virtual DbSet<Acessorio> Acessorios { get; set; }
        public virtual DbSet<Municao> Municoes { get; set; }
        public virtual DbSet<Armamento> Armamentos { get; set; }
        public virtual DbSet<Usuario> Usuarios { get; set; }
        public virtual DbSet<Operador> Operadores { get; set; }
        public virtual DbSet<Operacao> Operacaos { get; set; }

    }
}
